/* ------------------------------------------------------------------
   Données du quiz.
   RAW  : [code ISO, nom, capitale, continent, alias du nom, alias de la capitale]
   HIST : anciens drapeaux (images tirées de Wikimedia Commons)
   Continents : E Europe, A Asie, F Afrique, N Amérique du Nord (avec centrale
   et Caraïbes), S Amérique du Sud, O Océanie.
------------------------------------------------------------------- */
(function (root) {
  "use strict";

  const RAW = [
    // Europe
    ["al","Albanie","Tirana","E"],
    ["de","Allemagne","Berlin","E"],
    ["ad","Andorre","Andorre-la-Vieille","E",[],["andorra la vella"]],
    ["at","Autriche","Vienne","E",[],["vienna"]],
    ["be","Belgique","Bruxelles","E",[],["brussels"]],
    ["by","Biélorussie","Minsk","E",["bélarus","belarus"]],
    ["ba","Bosnie-Herzégovine","Sarajevo","E",["bosnie"]],
    ["bg","Bulgarie","Sofia","E"],
    ["cy","Chypre","Nicosie","E",[],["nicosia"]],
    ["hr","Croatie","Zagreb","E"],
    ["dk","Danemark","Copenhague","E",[],["copenhagen"]],
    ["es","Espagne","Madrid","E"],
    ["ee","Estonie","Tallinn","E"],
    ["fi","Finlande","Helsinki","E"],
    ["fr","France","Paris","E"],
    ["gr","Grèce","Athènes","E",[],["athens"]],
    ["hu","Hongrie","Budapest","E"],
    ["ie","Irlande","Dublin","E"],
    ["is","Islande","Reykjavik","E"],
    ["it","Italie","Rome","E"],
    ["xk","Kosovo","Pristina","E",[],["prishtina"]],
    ["lv","Lettonie","Riga","E"],
    ["li","Liechtenstein","Vaduz","E"],
    ["lt","Lituanie","Vilnius","E"],
    ["lu","Luxembourg","Luxembourg","E",[],["luxembourg ville"]],
    ["mk","Macédoine du Nord","Skopje","E",["macédoine"]],
    ["mt","Malte","La Valette","E",[],["valletta"]],
    ["md","Moldavie","Chisinau","E",["moldova"],["kichinev"]],
    ["mc","Monaco","Monaco","E"],
    ["me","Monténégro","Podgorica","E"],
    ["no","Norvège","Oslo","E"],
    ["nl","Pays-Bas","Amsterdam","E",["hollande"]],
    ["pl","Pologne","Varsovie","E",[],["warsaw"]],
    ["pt","Portugal","Lisbonne","E",[],["lisbon"]],
    ["ro","Roumanie","Bucarest","E",[],["bucharest"]],
    ["gb","Royaume-Uni","Londres","E",["uk","grande-bretagne"],["london"]],
    ["ru","Russie","Moscou","E",["fédération de russie"],["moscow"]],
    ["sm","Saint-Marin","Saint-Marin","E",[],["san marino"]],
    ["rs","Serbie","Belgrade","E"],
    ["sk","Slovaquie","Bratislava","E"],
    ["si","Slovénie","Ljubljana","E"],
    ["se","Suède","Stockholm","E"],
    ["ch","Suisse","Berne","E",[],["bern"]],
    ["cz","Tchéquie","Prague","E",["république tchèque"]],
    ["ua","Ukraine","Kiev","E",[],["kyiv"]],
    ["va","Vatican","Vatican","E",["cité du vatican","saint-siège"],["cité du vatican"]],

    // Asie
    ["af","Afghanistan","Kaboul","A",[],["kabul"]],
    ["sa","Arabie saoudite","Riyad","A",["arabie"],["riyadh"]],
    ["am","Arménie","Erevan","A",[],["yerevan"]],
    ["az","Azerbaïdjan","Bakou","A",[],["baku"]],
    ["bh","Bahreïn","Manama","A"],
    ["bd","Bangladesh","Dacca","A",[],["dhaka"]],
    ["bt","Bhoutan","Thimphou","A",[],["thimphu"]],
    ["mm","Birmanie","Naypyidaw","A",["myanmar"],["nay pyi taw","naypyitaw"]],
    ["bn","Brunei","Bandar Seri Begawan","A",[],["bandar"]],
    ["kh","Cambodge","Phnom Penh","A"],
    ["cn","Chine","Pékin","A",[],["beijing"]],
    ["kp","Corée du Nord","Pyongyang","A"],
    ["kr","Corée du Sud","Séoul","A",[],["seoul"]],
    ["ae","Émirats arabes unis","Abou Dabi","A",["eau","emirats"],["abu dhabi"]],
    ["ge","Géorgie","Tbilissi","A",[],["tbilisi"]],
    ["in","Inde","New Delhi","A",[],["delhi"]],
    ["id","Indonésie","Jakarta","A"],
    ["iq","Irak","Bagdad","A",[],["baghdad"]],
    ["ir","Iran","Téhéran","A",[],["tehran"]],
    ["il","Israël","Jérusalem","A",[],["jerusalem"]],
    ["jp","Japon","Tokyo","A"],
    ["jo","Jordanie","Amman","A"],
    ["kz","Kazakhstan","Astana","A",[],["nur-sultan"]],
    ["kg","Kirghizistan","Bichkek","A",["kirghizstan","kyrgyzstan"],["bishkek"]],
    ["kw","Koweït","Koweït","A",["kuwait"],["koweit city","kuwait city"]],
    ["la","Laos","Vientiane","A"],
    ["lb","Liban","Beyrouth","A",[],["beirut"]],
    ["my","Malaisie","Kuala Lumpur","A",[],["putrajaya"]],
    ["mv","Maldives","Malé","A"],
    ["mn","Mongolie","Oulan-Bator","A",[],["ulaanbaatar"]],
    ["np","Népal","Katmandou","A",[],["kathmandu"]],
    ["om","Oman","Mascate","A",[],["muscat"]],
    ["uz","Ouzbékistan","Tachkent","A",[],["tashkent"]],
    ["pk","Pakistan","Islamabad","A"],
    ["ps","Palestine","Jérusalem-Est","A",[],["ramallah","jerusalem","jerusalem est"]],
    ["ph","Philippines","Manille","A",[],["manila"]],
    ["qa","Qatar","Doha","A"],
    ["sg","Singapour","Singapour","A",[],["singapore"]],
    ["lk","Sri Lanka","Sri Jayawardenapura-Kotté","A",["ceylan"],["colombo","kotte"]],
    ["sy","Syrie","Damas","A",[],["damascus"]],
    ["tj","Tadjikistan","Douchanbé","A",[],["dushanbe"]],
    ["tw","Taïwan","Taipei","A"],
    ["th","Thaïlande","Bangkok","A"],
    ["tl","Timor oriental","Dili","A",["timor-leste"]],
    ["tm","Turkménistan","Achgabat","A",[],["ashgabat"]],
    ["tr","Turquie","Ankara","A",["turkiye"]],
    ["vn","Vietnam","Hanoï","A",[],["hanoi"]],
    ["ye","Yémen","Sanaa","A",[],["sana"]],

    // Afrique
    ["za","Afrique du Sud","Pretoria","F",[],["le cap","cape town","bloemfontein"]],
    ["dz","Algérie","Alger","F",[],["algiers"]],
    ["ao","Angola","Luanda","F"],
    ["bj","Bénin","Porto-Novo","F",[],["cotonou"]],
    ["bw","Botswana","Gaborone","F"],
    ["bf","Burkina Faso","Ouagadougou","F"],
    ["bi","Burundi","Gitega","F",[],["bujumbura"]],
    ["cm","Cameroun","Yaoundé","F"],
    ["cv","Cap-Vert","Praia","F",["cabo verde"]],
    ["cf","République centrafricaine","Bangui","F",["centrafrique","rca"]],
    ["km","Comores","Moroni","F"],
    ["cg","République du Congo","Brazzaville","F",["congo","congo-brazzaville"]],
    ["cd","République démocratique du Congo","Kinshasa","F",["rdc","rd congo","congo-kinshasa"]],
    ["ci","Côte d'Ivoire","Yamoussoukro","F",[],["abidjan"]],
    ["dj","Djibouti","Djibouti","F"],
    ["eg","Égypte","Le Caire","F",[],["cairo"]],
    ["er","Érythrée","Asmara","F"],
    ["sz","Eswatini","Mbabane","F",["swaziland"],["lobamba"]],
    ["et","Éthiopie","Addis-Abeba","F",[],["addis ababa"]],
    ["ga","Gabon","Libreville","F"],
    ["gm","Gambie","Banjul","F"],
    ["gh","Ghana","Accra","F"],
    ["gn","Guinée","Conakry","F"],
    ["gw","Guinée-Bissau","Bissau","F"],
    ["gq","Guinée équatoriale","Malabo","F"],
    ["ke","Kenya","Nairobi","F"],
    ["ls","Lesotho","Maseru","F"],
    ["lr","Libéria","Monrovia","F",["liberia"]],
    ["ly","Libye","Tripoli","F"],
    ["mg","Madagascar","Antananarivo","F",[],["tananarive"]],
    ["mw","Malawi","Lilongwe","F"],
    ["ml","Mali","Bamako","F"],
    ["ma","Maroc","Rabat","F"],
    ["mu","Maurice","Port-Louis","F",["île maurice"]],
    ["mr","Mauritanie","Nouakchott","F"],
    ["mz","Mozambique","Maputo","F"],
    ["na","Namibie","Windhoek","F"],
    ["ne","Niger","Niamey","F"],
    ["ng","Nigeria","Abuja","F"],
    ["ug","Ouganda","Kampala","F"],
    ["rw","Rwanda","Kigali","F"],
    ["st","Sao Tomé-et-Principe","São Tomé","F",["sao tome"],["sao tome"]],
    ["sn","Sénégal","Dakar","F"],
    ["sc","Seychelles","Victoria","F"],
    ["sl","Sierra Leone","Freetown","F"],
    ["so","Somalie","Mogadiscio","F",[],["mogadishu"]],
    ["sd","Soudan","Khartoum","F"],
    ["ss","Soudan du Sud","Djouba","F",[],["juba"]],
    ["tz","Tanzanie","Dodoma","F",[],["dar es salaam"]],
    ["td","Tchad","N'Djamena","F",[],["ndjamena"]],
    ["tg","Togo","Lomé","F"],
    ["tn","Tunisie","Tunis","F"],
    ["zm","Zambie","Lusaka","F"],
    ["zw","Zimbabwe","Harare","F"],

    // Amérique du Nord, centrale et Caraïbes
    ["ag","Antigua-et-Barbuda","Saint John's","N",["antigua"]],
    ["bs","Bahamas","Nassau","N"],
    ["bb","Barbade","Bridgetown","N"],
    ["bz","Belize","Belmopan","N"],
    ["ca","Canada","Ottawa","N"],
    ["cr","Costa Rica","San José","N",[],["san jose"]],
    ["cu","Cuba","La Havane","N",[],["havana"]],
    ["dm","Dominique","Roseau","N"],
    ["do","République dominicaine","Saint-Domingue","N",["dominicaine"],["santo domingo"]],
    ["sv","Salvador","San Salvador","N",["el salvador"]],
    ["us","États-Unis","Washington","N",["usa","us","etats-unis d'amerique"],["washington dc","washington d.c."]],
    ["gd","Grenade","Saint-Georges","N"],
    ["gt","Guatemala","Guatemala","N",[],["guatemala city"]],
    ["ht","Haïti","Port-au-Prince","N"],
    ["hn","Honduras","Tegucigalpa","N"],
    ["jm","Jamaïque","Kingston","N"],
    ["mx","Mexique","Mexico","N",[],["mexico city","ville de mexico"]],
    ["ni","Nicaragua","Managua","N"],
    ["pa","Panama","Panama","N",[],["panama city"]],
    ["kn","Saint-Christophe-et-Niévès","Basseterre","N",["saint-kitts-et-nevis","saint kitts","saint-christophe"]],
    ["lc","Sainte-Lucie","Castries","N"],
    ["vc","Saint-Vincent-et-les-Grenadines","Kingstown","N",["saint-vincent"]],
    ["tt","Trinité-et-Tobago","Port-d'Espagne","N",["trinité"],["port of spain"]],

    // Amérique du Sud
    ["ar","Argentine","Buenos Aires","S"],
    ["bo","Bolivie","Sucre","S",[],["la paz"]],
    ["br","Brésil","Brasilia","S"],
    ["cl","Chili","Santiago","S"],
    ["co","Colombie","Bogota","S"],
    ["ec","Équateur","Quito","S"],
    ["gy","Guyana","Georgetown","S"],
    ["py","Paraguay","Asunción","S"],
    ["pe","Pérou","Lima","S"],
    ["sr","Suriname","Paramaribo","S"],
    ["uy","Uruguay","Montevideo","S"],
    ["ve","Venezuela","Caracas","S"],

    // Océanie
    ["au","Australie","Canberra","O"],
    ["fj","Fidji","Suva","O"],
    ["mh","Îles Marshall","Majuro","O",["marshall"]],
    ["sb","Îles Salomon","Honiara","O",["salomon"]],
    ["ki","Kiribati","Tarawa-Sud","O",[],["tarawa","south tarawa"]],
    ["fm","Micronésie","Palikir","O",["états fédérés de micronésie"]],
    ["nr","Nauru","Yaren","O"],
    ["nz","Nouvelle-Zélande","Wellington","O"],
    ["pw","Palaos","Ngerulmud","O",["palau"],["melekeok"]],
    ["pg","Papouasie-Nouvelle-Guinée","Port Moresby","O",["papouasie"]],
    ["ws","Samoa","Apia","O"],
    ["to","Tonga","Nukuʻalofa","O"],
    ["tv","Tuvalu","Funafuti","O"],
    ["vu","Vanuatu","Port-Vila","O"]
  ];

  /* Anciens drapeaux.
     files : noms de fichiers Wikimedia Commons, essayés dans l'ordre.
             (Si aucun ne charge, la question est sautée automatiquement.)  */
  const HIST = [
    { id:"urss", c:"E", name:"URSS",
      alt:["union soviétique","union des républiques socialistes soviétiques","ussr"],
      files:["Flag_of_the_Soviet_Union.svg"],
      period:"1955–1991", note:"Aujourd'hui : Russie, Ukraine, Biélorussie, Kazakhstan et onze autres pays." },
    { id:"yougoslavie", c:"E", name:"Yougoslavie",
      alt:["république fédérative socialiste de yougoslavie"],
      files:["Flag_of_Yugoslavia_(1946-1992).svg","Flag_of_Yugoslavia_(1946–1992).svg"],
      period:"1946–1992", note:"Éclatée en Serbie, Croatie, Slovénie, Bosnie-Herzégovine, Monténégro, Macédoine du Nord et Kosovo." },
    { id:"tchecoslovaquie", c:"E", name:"Tchécoslovaquie", alt:[],
      files:["Flag_of_Czechoslovakia.svg"],
      period:"1920–1992", note:"Séparée en Tchéquie et Slovaquie le 1er janvier 1993." },
    { id:"rda", c:"E", name:"RDA",
      alt:["république démocratique allemande","allemagne de l'est","ddr"],
      files:["Flag_of_East_Germany.svg"],
      period:"1959–1990", note:"Réunifiée avec la RFA le 3 octobre 1990." },
    { id:"serbiemontenegro", c:"E", name:"Serbie-et-Monténégro",
      alt:["union d'état de serbie-et-monténégro"],
      files:["Flag_of_Serbia_and_Montenegro.svg","Flag_of_Serbia_and_Montenegro_(2003–2006).svg"],
      period:"2003–2006", note:"Le Monténégro a proclamé son indépendance en 2006." },
    { id:"prusse", c:"E", name:"Prusse", alt:["royaume de prusse"],
      files:["Flag_of_Prussia_(1892-1918).svg","Flag_of_Prussia_(1892–1918).svg"],
      period:"1892–1918", note:"Cœur de l'Empire allemand, aboli après 1918." },
    { id:"autrichehongrie", c:"E", name:"Autriche-Hongrie",
      alt:["empire austro-hongrois","austro-hongrie"],
      files:["Flag_of_Austria-Hungary_(1867-1918).svg","Flag_of_Austria-Hungary_(1867–1918).svg"],
      period:"1867–1918", note:"Dissoute à la fin de la Première Guerre mondiale." },
    { id:"boheme", c:"E", name:"Bohême", alt:["royaume de bohême"],
      files:["Flag_of_Bohemia.svg"],
      period:"Depuis le Moyen Âge", note:"Aujourd'hui : l'ouest de la Tchéquie." },
    { id:"italieroyale", c:"E", name:"Italie", alt:["royaume d'italie"],
      files:["Flag_of_Italy_(1861–1946).svg","Flag_of_Italy_(1861-1946).svg"],
      period:"1861–1946", note:"Royaume d'Italie : tricolore avec les armes de la Maison de Savoie." },
    { id:"roumanie", c:"E", name:"Roumanie",
      alt:["république socialiste de roumanie"],
      files:["Flag_of_Romania_(1965–1989).svg","Flag_of_Romania_(1965-1989).svg"],
      period:"1965–1989", note:"Avec les armes communistes, avant la révolution de 1989." },
    { id:"espagnefranco", c:"E", name:"Espagne",
      alt:["espagne franquiste"],
      files:["Flag_of_Spain_(1945–1977).svg","Flag_of_Spain_(1945-1977).svg"],
      period:"1945–1977", note:"Époque franquiste, avec l'aigle de saint Jean." },
    { id:"ottoman", c:"A", name:"Empire ottoman",
      alt:["ottoman","empire turc","ottomans"],
      files:["Flag_of_the_Ottoman_Empire_(1844–1922).svg","Flag_of_the_Ottoman_Empire.svg","Flag_of_the_Ottoman_Empire_(1844-1922).svg"],
      period:"1844–1922", note:"Aujourd'hui : Turquie, et une grande partie du Proche-Orient et des Balkans." },
    { id:"tibet", c:"A", name:"Tibet", alt:[],
      files:["Flag_of_Tibet.svg"],
      period:"1912–1950", note:"Intégré à la Chine en 1950–1951." },
    { id:"sudvietnam", c:"A", name:"Vietnam du Sud",
      alt:["république du vietnam","sud vietnam","sud-vietnam"],
      files:["Flag_of_South_Vietnam.svg"],
      period:"1955–1975", note:"Réunifié avec le Nord en 1976." },
    { id:"kampuchea", c:"A", name:"Cambodge",
      alt:["kampuchéa","kampuchéa démocratique","kampuchea"],
      files:["Flag_of_Democratic_Kampuchea.svg"],
      period:"1975–1979", note:"Kampuchéa démocratique, sous les Khmers rouges." },
    { id:"rau", c:"A", name:"République arabe unie",
      alt:["rau","egypte et syrie","union de l'egypte et de la syrie"],
      files:["Flag_of_the_United_Arab_Republic.svg","Flag_of_United_Arab_Republic.svg"],
      period:"1958–1961", note:"Union de l'Égypte et de la Syrie." },
    { id:"yemensud", c:"A", name:"Yémen du Sud",
      alt:["république démocratique populaire du yémen","sud yémen","sud-yémen"],
      files:["Flag_of_South_Yemen.svg"],
      period:"1967–1990", note:"Réunifié avec le Nord en 1990." },
    { id:"hongkong", c:"A", name:"Hong Kong", alt:["hongkong"],
      files:["Flag_of_Hong_Kong_(1959–1997).svg","Flag_of_Hong_Kong_(1959-1997).svg"],
      period:"1959–1997", note:"Colonie britannique, rétrocédée à la Chine en 1997." },
    { id:"iranshah", c:"A", name:"Iran",
      alt:["perse","empire d'iran"],
      files:["Flag_of_Iran_(1964–1980).svg","Flag_of_Iran_(1964-1980).svg"],
      period:"1964–1980", note:"Drapeau impérial au lion et au soleil, avant la révolution islamique." },
    { id:"georgie", c:"A", name:"Géorgie", alt:[],
      files:["Flag_of_Georgia_(1990–2004).svg","Flag_of_Georgia_(1990-2004).svg"],
      period:"1990–2004", note:"Remplacé par le drapeau des cinq croix après la révolution des Roses." },
    { id:"zaire", c:"F", name:"Zaïre", alt:["république du zaïre"],
      files:["Flag_of_Zaire.svg"],
      period:"1971–1997", note:"Aujourd'hui : République démocratique du Congo." },
    { id:"rhodesie", c:"F", name:"Rhodésie", alt:["rhodesia"],
      files:["Flag_of_Rhodesia.svg"],
      period:"1968–1979", note:"Aujourd'hui : Zimbabwe." },
    { id:"apartheid", c:"F", name:"Afrique du Sud",
      alt:["afrique du sud de l'apartheid"],
      files:["Flag_of_South_Africa_(1928–1994).svg","Flag_of_South_Africa_(1928-1994).svg"],
      period:"1928–1994", note:"Drapeau de l'apartheid, remplacé après les premières élections libres." },
    { id:"libye", c:"F", name:"Libye", alt:[],
      files:["Flag_of_Libya_(1977–2011).svg","Flag_of_Libya_(1977-2011).svg"],
      period:"1977–2011", note:"Drapeau entièrement vert, sous Kadhafi." },
    { id:"katanga", c:"F", name:"Katanga", alt:["etat du katanga"],
      files:["Flag_of_Katanga.svg"],
      period:"1960–1963", note:"Sécession de la République démocratique du Congo." },
    { id:"biafra", c:"F", name:"Biafra", alt:["république du biafra"],
      files:["Flag_of_Biafra.svg"],
      period:"1967–1970", note:"Sécession du Nigeria, suivie d'une guerre et d'une famine." },
    { id:"congolibre", c:"F", name:"État indépendant du Congo",
      alt:["état libre du congo","congo belge","congo léopoldville"],
      files:["Flag_of_the_Congo_Free_State.svg"],
      period:"1885–1908", note:"Propriété personnelle du roi Léopold II, puis Congo belge." },
    { id:"rwanda", c:"F", name:"Rwanda", alt:[],
      files:["Flag_of_Rwanda_(1962–2001).svg","Flag_of_Rwanda_(1962-2001).svg"],
      period:"1962–2001", note:"Avec le grand R noir, remplacé après le génocide de 1994." },
    { id:"malawi", c:"F", name:"Malawi", alt:[],
      files:["Flag_of_Malawi_(1964–2010).svg","Flag_of_Malawi_(1964-2010).svg"],
      period:"1964–2010", note:"Avec le soleil levant, brièvement remplacé de 2010 à 2012." },
    { id:"hawai", c:"O", name:"Hawaï", alt:["hawaii","royaume d'hawaï"],
      files:["Flag_of_Hawaii.svg"],
      period:"Royaume de 1816 à 1893", note:"Devenu un État américain en 1959. Le drapeau est toujours celui de l'État." }
  ];

  const DATA = { RAW: RAW, HIST: HIST };
  if (typeof module !== "undefined" && module.exports) module.exports = DATA;
  else root.DATA = DATA;
})(typeof window !== "undefined" ? window : globalThis);
